apiVersion: v1
kind: Service
metadata:
#  namespace: ns1
  name: ms-nginx-srv
spec:
  type: NodePort
  ports:
    - port: 8082
      targetPort: 80
  selector:
    app: ms-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
#  namespace: ns1
  name: ms-nginx-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-app
  template:
    metadata:
      labels:
        app: ms-app
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.3
          ports:
            - containerPort: 80