apiVersion: v1
kind: Service
metadata:
  namespace: ns1
  name: ms-srv-with-lb-service
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 80
  selector:
    app: ms-srv-with-lb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ns1
  name: ms-srv-with-lb-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-srv-with-lb
  template:
    metadata:
      labels:
        app: ms-srv-with-lb
    spec:
      containers:
        - name: nginx
          image: nginx:1.17.3
          ports:
            - containerPort: 80