management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-components: always
      show-details: always

  # Generic OpenTelemetry configuration (partially shared between metrics and traces)
  opentelemetry:
    resource-attributes:
      application: ${spring.application.name}
      cluster: local
      # Micrometer Metrics configures this attribute with "unknown value".
      # It should probably be autoconfigured correctly by Spring Boot.
      "service.name": ${spring.application.name}

  otlp:
  # Traces-specific OpenTelemetry configuration
    tracing:
      endpoint: http://otlp14268.kube.local/v1/traces
  # Metrics-specific OpenTelemetry configuration
    metrics:
      export:
        url: http://otlp8888.kube.local/api/v1/otlp
        step: 5s