apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ns1
  name: gateway-role
rules:
  - apiGroups: ["apis","apps","apis/apps",""]
    resources: ["deployments","endpoints","pods","services"]
    verbs: ["get", "list", "watch"]


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: ns1
  name: gateway-role-binding
subjects:
  - kind: ServiceAccount
    name: gateway-service-account
    namespace: ns1
roleRef:
  kind: Role
  name: gateway-role
  apiGroup: rbac.authorization.k8s.io
