apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: ns1
  name: gateway-sa
automountServiceAccountToken: false

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ns1
  name: namespace-reader-role
rules:
  - apiGroups: [ "" ]
    resources: [ "configmaps", "deployments","pods", "services", "endpoints", "secrets", "endpointslices" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "apps" ]
    resources: [ "configmaps", "deployments","pods", "services", "endpoints", "secrets", "endpointslices" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "discovery.k8s.io" ]
    resources: [ "configmaps", "deployments","pods", "services", "endpoints", "secrets", "endpointslices" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "extensions" ]
    resources: [ "configmaps", "deployments","pods", "services", "endpoints", "secrets", "endpointslices" ]
    verbs: [ "get", "list", "watch" ]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: namespace-reader-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: namespace-reader-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: ns1


#  - kind: User
#    name: system:anonymous # Name is case sensitive
#    apiGroup: rbac.authorization.k8s.io

